### ISSUE TITLE
Support for Cabal version 3.0

### ISSUE THREAD

**Issue by emilypi** [commercialhaskell/curator#15]
See https://github.com/commercialhaskell/stackage/pull/5357#issuecomment-628997604

**Comment by juhp** [comment]
```
curator: Unable to parse cabal file from package strict-tuple-lens-0.1.0.0@sha256:aac6e617af201749dc328d237fcd2099a4950b6d6a4cc2fc2
47a77480c1bca56,1360 (from Hackage)

- 0:0: Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899.

The cabal file uses the cabal specification version 3.0, but we only support up to version 2.4.
```

(since been worked around with a newer release of strict-tuple-lens).

**Comment by juhp** [comment]
Ah, is this just a matter of bumping `cabal-format-version`??

https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L8

**Comment by snoyberg** [comment]
@juhp did that end up fixing it? Can this be closed?

**Comment by juhp** [comment]
Well I believe we support 3.0 in Stackage/curator now, so I think we could close this. (I believe at the time the requestor reverted to 2.4.)

**Comment by emilypi** [comment]
I changed to `cabal-version: 2.2`, so I can't confirm this for you, unfortunately.
