### ISSUE TITLE
'text' flags not included in generated snapshots

### ISSUE THREAD

**Issue by googleson78** [commercialhaskell/curator#16]
I think the `curator` is not generating flags for `text`. The issue, I believe, is that `text` is not included in `build-constraints.yaml` as a `package`, and so `Curator.Stackage.convert` doesn't look at its flags at all.

However if I patch `Curator.Stackage.convert` to consider `package-flags` separately it would then have to include `text` in `Constraints.consPackages` (which is probably undesired (?) because `text` ships with `ghc`).

So I guess `Constraints` should get some additional field in which to store flags? And they can then be removed from `PackageConstraints`?

Related issues:
https://github.com/commercialhaskell/stack/issues/5307
https://github.com/commercialhaskell/stackage/issues/5409

**Comment by snoyberg** [comment]
I don't see a motivation why this should be different than it is right now. `text` is not part of the snapshot, it's part of the global package database. We used to include information about those package in snapshots, but it was inaccurate, as demonstrated by multiple GHC versions shipping versions of libraries that don't exist on Hackage at all.

**Comment by googleson78** [comment]
What is the proper way of telling `stack` to use the `integer-simple` flag for `text`?

`--flag text:integer-simple` [doesn't work](https://github.com/commercialhaskell/stack/issues/5307). 

Does this mean that this is a bug in `stack` and it should be looking in the global package database by default?

**Comment by snoyberg** [comment]
You need to specify `text` and its flags in the `stack.yaml` file.

**Comment by qrilka** [comment]
or in a custom snapshot if that could make sense

**Comment by googleson78** [comment]
Thanks, I'll move the discussion [back to `stack`](https://github.com/commercialhaskell/stack/issues/5307#issuecomment-644000404).
