### ISSUE TITLE
distro upload to Hackage failing with IncompleteHeaders

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/curator#8]
For a good while Stackage distro uploads to Hackage have been failing like this:

```
:
To github.com:commercialhaskell/stackage-snapshots
   3eb56ec..cdae8cd  HEAD -> master
Uploading Hackage distro for snapshot.yaml
Uploading as Hackage distro: Stackage
curator: HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Authorization","<REDACTED>"),("Content-Type","text/csv")]
  path                 = "/distro/Stackage/packages.csv"
  queryString          = ""
  method               = "PUT"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 IncompleteHeaders
Fri Jan 24 18:00:28 UTC 2020
```
I am not clear what the exact cause is.

**Comment by snoyberg** [comment]
`IncompleteHeaders` indicates that Hackage is not responding with a valid HTTP response.

**Comment by juhp** [comment]
Do you have a suggestion for how best to debug this further, ie to work out what wrong with the response?

**Comment by snoyberg** [comment]
I would try making a manual request via something like `curl` and see if it succeeds or fails. Then I'd try making the same request with a usage of the `http-conduit` library.

**Comment by juhp** [comment]
Oh curl works - that is what I do for Fedora :)
Okay thanks I will try playing with this later.

**Comment by juhp** [comment]
> Then I'd try making the same request with a usage of the `http-conduit` library.

Today finally I implemented this for Fedora in https://github.com/fedora-haskell/fedora-haskell-tools/commit/430c8541d5ddf1313b2102461e407ebee37ad67c and it works just fine...
(previously I only generated the CSV in Haskell and then lazily uploaded that with curl.)

**Comment by juhp** [comment]
I managed to finally do some debugging in the Stackage builder container.

Basically the problem is the raw Show strings from `displayShow name'` and `displayShow version` in HackageDistro.hs which put into the uploaded csv package data.
