### ISSUE TITLE
rejecting incorrectly-placed constraints.yaml fields

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/curator#9]
The `range` field should be under `source` in constraints.yaml (for LTS etc).

However it is possible to put it in the wrong place, ie not under `source`, which then does nothing (or rather is a time-bomb for the following week's lts).
It would be nice to fail parsing in that case, or liberally (probably harder) allow range there.
Perhaps a warning about unknown fields could also help if not there, maybe also harder.

**Comment by juhp** [comment]
Any suggestion for how to do that?

**Comment by juhp** [comment]
Hmm I think that would require TH, which curator doesn't use AFAICT

**Comment by bergmark** [comment]
It should be doable with generics as well. But if it's manually written instances then it needs to be manually implemented of course...

If this is the same deserialization as stack uses then we probably don't want to change it as it would make it very hard to manage compatibility. Perhaps a custom validation step would make more sense?

**Comment by bergmark** [comment]
Not an issue with the new workflow.
